apiVersion: v1
kind: Service
metadata:
  labels:
    app: jsonplaceholder-sidecar
  name: sidecar
  namespace: gateway
spec:
  ports:
  - name: 80-80
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jsonplaceholder-sidecar
  type: NodePort