apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
  name: flex-gateway:gateway:gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flex-gateway:gateway:gateway
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: gateway
- kind: ServiceAccount
  name: default
  namespace: gateway
  